version: "1.0"
info:
  model: int-scaffold
packages:
- name: Dada4Project
  gitServerName: sumitaShared
  gitUrl: https://github.com/sumitaPriyadarshy
  gitUsername: sumitaPriyadarshy
  gitBranch: main
services:
- serviceName: project.dada4.integrations:test1
  packages:
  - name: Dada4Project
    version: "1.0"
